services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: evalap-app:dev
    ports:
      - "8000:8000"
      - "8501:8501" 
    command: ["supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
